# Generated by Django 4.1.5 on 2023-01-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0004_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_electric',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='historical_gas',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='historical_weather',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
